name: github action test
on:
  push:
    branches: ['master']
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: github CI CD
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            pwd
            cd hermes
            git pull
            docker-compose up -d
            
