name: deploy CI CD test

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Change Directory
        run: |
          cd /home/dkadmin/hermes

      - name: Git Pull
        run: |
          git pull

      - name: Docker Compose Up
        run: |
          sudo docker-compose up -d
